openapi: '3.0.2'
info:
  title: Customer notifications
  version: '1.0'
servers:
  - url: https://localhost:5001/v1
paths:
  /Message/CustomerNotification/Customer1:
    get:
      responses:
        '200':
          description: OK